import '../styles/global.css';
import { Metadata } from 'next';
import ClientProvider from '../components/ClientProvider';
import React from 'react';

export const metadata: Metadata = {
	title: 'Planets',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<head>
				<link rel="icon" href="/vite.svg" type="image/png" />
				<title>Planets</title>
			</head>
			<body>
				<ClientProvider>{children}</ClientProvider>
			</body>
		</html>
	);
}
